# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsalbum',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注信息'),
        ),
    ]
