# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-09 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='place',
        ),
        migrations.AddField(
            model_name='address',
            name='place2',
            field=models.CharField(max_length=50, null=True, verbose_name='详细地址'),
        ),
    ]
