# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-09 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180909_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='place2',
            new_name='place',
        ),
    ]
