# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-09 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180909_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='place',
            field=models.CharField(max_length=50, verbose_name='详细地址'),
        ),
    ]
