# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-12 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180909_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '用户地址', 'verbose_name_plural': '用户地址'},
        ),
    ]
